-- GENERATED by C->Haskell Compiler, version 0.28.8 Switcheroo, 25 November 2017 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Raw.chs" #-}
{-# LANGUAGE CApiFFI                    #-}
{-# LANGUAGE ForeignFunctionInterface   #-}

module ImGui.Raw
  ( createContext
  , destroyContext
  , getCurrentContext
  , begin
  , end
  , button
  , selectable
  , beginListBox
  , endListBox
  , beginGroup
  , endGroup
  , module ImGui.Raw.Structs
  , module ImGui.Raw.Types) where
import qualified Foreign.C.String as C2HSImp
import qualified Foreign.C.Types as C2HSImp
import qualified Foreign.Marshal.Utils as C2HSImp
import qualified Foreign.Ptr as C2HSImp



import           Foreign
import           Foreign.C.String
import           Foreign.C.Types
import Foreign.Marshal.Utils (with)

import ImGui.Raw.Structs
import ImGui.Raw.Types





-- System
--- Context
createContext :: (FontAtlas) -> IO ((Context))
createContext a1 =
  let {a1' = id a1} in 
  createContext'_ a1' >>= \res ->
  let {res' = id res} in
  return (res')

{-# LINE 33 "Raw.chs" #-}

destroyContext :: (Context) -> IO ()
destroyContext a1 =
  let {a1' = id a1} in 
  destroyContext'_ a1' >>
  return ()

{-# LINE 34 "Raw.chs" #-}

getCurrentContext :: IO ((Context))
getCurrentContext =
  getCurrentContext'_ >>= \res ->
  let {res' = id res} in
  return (res')

{-# LINE 35 "Raw.chs" #-}


--- Frame
newFrame :: IO ()
newFrame =
  newFrame'_ >>
  return ()

{-# LINE 38 "Raw.chs" #-}

endFrame :: IO ()
endFrame =
  endFrame'_ >>
  return ()

{-# LINE 39 "Raw.chs" #-}


--- Window
begin :: (String) -> ([WindowFlag]) -> IO ((Bool))
begin a1 a3 =
  C2HSImp.withCString a1 $ \a1' -> 
  alloca $ \a2' -> 
  let {a3' = combineWindowFlags a3} in 
  begin'_ a1' a2' a3' >>
  peek  a2'>>= \a2'' -> 
  return (a2'')

{-# LINE 46 "Raw.chs" #-}

end :: IO ()
end =
  end'_ >>
  return ()

{-# LINE 47 "Raw.chs" #-}


-- Widgets
--- Button
button :: (String) -> (ImVec2Ptr) -> IO ((Bool))
button a1 a2 =
  C2HSImp.withCString a1 $ \a1' -> 
  with a2 $ \a2' -> 
  button'_ a1' a2' >>= \res ->
  let {res' = C2HSImp.toBool res} in
  return (res')

{-# LINE 51 "Raw.chs" #-}


--- Selectable
selectable :: (String) -> (Bool) -> (CInt) -> (ImVec2Ptr) -> IO ((Bool))
selectable a1 a2 a3 a4 =
  C2HSImp.withCString a1 $ \a1' -> 
  let {a2' = C2HSImp.fromBool a2} in 
  let {a3' = fromIntegral a3} in 
  let {a4' = peek a4} in 
  selectable'_ a1' a2' a3' a4' >>= \res ->
  let {res' = C2HSImp.toBool res} in
  return (res')

{-# LINE 59 "Raw.chs" #-}


--- Listbox
beginListBox :: (String) -> (ImVec2Ptr) -> IO ((Bool))
beginListBox a1 a2 =
  C2HSImp.withCString a1 $ \a1' -> 
  let {a2' = id a2} in 
  beginListBox'_ a1' a2' >>= \res ->
  let {res' = C2HSImp.toBool res} in
  return (res')

{-# LINE 62 "Raw.chs" #-}


endListBox :: IO ()
endListBox =
  endListBox'_ >>
  return ()

{-# LINE 64 "Raw.chs" #-}


--- Group
beginGroup :: IO ()
beginGroup =
  beginGroup'_ >>
  return ()

{-# LINE 67 "Raw.chs" #-}

endGroup :: IO ()
endGroup =
  endGroup'_ >>
  return ()

{-# LINE 68 "Raw.chs" #-}


foreign import ccall unsafe "Raw.chs.h igCreateContext"
  createContext'_ :: ((C2HSImp.Ptr ()) -> (IO (C2HSImp.Ptr ())))

foreign import ccall unsafe "Raw.chs.h igDestroyContext"
  destroyContext'_ :: ((C2HSImp.Ptr ()) -> (IO ()))

foreign import ccall unsafe "Raw.chs.h igGetCurrentContext"
  getCurrentContext'_ :: (IO (C2HSImp.Ptr ()))

foreign import ccall unsafe "Raw.chs.h igNewFrame"
  newFrame'_ :: (IO ())

foreign import ccall unsafe "Raw.chs.h igEndFrame"
  endFrame'_ :: (IO ())

foreign import ccall unsafe "Raw.chs.h __c2hs_wrapped__igBegin"
  begin'_ :: ((C2HSImp.Ptr C2HSImp.CChar) -> ((C2HSImp.Ptr C2HSImp.CUChar{-bool-}) -> (C2HSImp.CInt -> (IO C2HSImp.CUChar{-bool-}))))

foreign import ccall unsafe "Raw.chs.h igEnd"
  end'_ :: (IO ())

foreign import ccall unsafe "Raw.chs.h __c2hs_wrapped__igButton"
  button'_ :: ((C2HSImp.Ptr C2HSImp.CChar) -> ((C2HSImp.Ptr ()) -> (IO C2HSImp.CUChar{-bool-})))

foreign import ccall unsafe "Raw.chs.h __c2hs_wrapped__igSelectable_Bool"
  selectable'_ :: ((C2HSImp.Ptr C2HSImp.CChar) -> (C2HSImp.CUChar{-bool-} -> (C2HSImp.CInt -> ((C2HSImp.Ptr ()) -> (IO C2HSImp.CUChar{-bool-})))))

foreign import ccall safe "Raw.chs.h __c2hs_wrapped__igBeginListBox"
  beginListBox'_ :: ((C2HSImp.Ptr C2HSImp.CChar) -> ((C2HSImp.Ptr ()) -> (IO C2HSImp.CUChar{-bool-})))

foreign import ccall unsafe "Raw.chs.h igEndListBox"
  endListBox'_ :: (IO ())

foreign import ccall unsafe "Raw.chs.h igBeginGroup"
  beginGroup'_ :: (IO ())

foreign import ccall unsafe "Raw.chs.h igEndGroup"
  endGroup'_ :: (IO ())
